### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ramajoballester** [CRTM-NFC/Mifare-Desfire#1]
Hi, @mgp25,

I would like to know the current status of this project, since it is really amazing. Is there anything I could be of help with? I'm another madrileño trying to descifer how the metro card works (:

**Comment by mgp25** [comment]
Hello @ramajoballester,

In this project we describe the standards, technology and procedures of how the NFC cards works. The rest of the operations to read/write would require keys, keys that are private and we don't have. If you had the keys, you would be able to do all operations you might want to do, however that is out of the scope of the project since it would be ilegal.

So answering to your question, if you wanted to know the decrypted stream or do operation, you would need the keys or discover any vulnerability. [[1]](https://github.com/CRTM-NFC/Mifare-Desfire#custom-apk-for-debugging-nfc-communication)

If you are still interested in learning how NFC card works, you can start looking into the Mifare Classic cards, they are a good introduction to the NFC field.

Best regards
